#pragma once
#define KEY CheckHitKey

#define BACK KEY(KEY_INPUT_BACK)	// バックスペースキー
#define TAB KEY(KEY_INPUT_TAB)	// タブキー
#define ENTER KEY(KEY_INPUT_RETURN)	// エンターキー
#define LSHIFT KEY(KEY_INPUT_LSHIFT)	// 左シフトキー
#define RSHIFT KEY(KEY_INPUT_RSHIFT)	// 右シフトキー
#define LCTRL KEY(KEY_INPUT_LCONTROL)	// 左コントロールキー
#define RCTRL KEY(KEY_INPUT_RCONTROL)	// 右コントロールキー
#define ESC KEY(KEY_INPUT_ESCAPE)	// エスケープキー
#define SPACE KEY(KEY_INPUT_SPACE)	// スペースキー
#define PUP KEY(KEY_INPUT_PGUP)	// ＰａｇｅＵＰキー
#define PDOWN KEY(KEY_INPUT_PGDN)	// ＰａｇｅＤｏｗｎキー
#define END KEY(KEY_INPUT_END)	// エンドキー
#define HOME KEY(KEY_INPUT_HOME)	// ホームキー
#define LEFT KEY(KEY_INPUT_LEFT)	// 左キー
#define UP KEY(KEY_INPUT_UP)	// 上キー
#define RIGHT KEY(KEY_INPUT_RIGHT)	// 右キー
#define DOWN KEY(KEY_INPUT_DOWN)	// 下キー
#define INS KEY(KEY_INPUT_INSERT)	// インサートキー
#define DEL KEY(KEY_INPUT_DELETE)	// デリートキー
#define MIN KEY(KEY_INPUT_MINUS)	// －キー
#define YEN KEY(KEY_INPUT_YEN)	// ￥キー
#define PREVTRACK KEY(KEY_INPUT_PREVTRACK)	// ＾キー
#define PIRIOD KEY(KEY_INPUT_PERIOD)	// ．キー
#define SLASH KEY(KEY_INPUT_SLASH)	// ／キー
#define LALT KEY(KEY_INPUT_LALT)	// 左ＡＬＴキー
#define RALT KEY(KEY_INPUT_RALT)	// 右ＡＬＴキー
#define SCROLL KEY(KEY_INPUT_SCROLL)	// ScrollLockキー
#define SEMCOLON KEY(KEY_INPUT_SEMICOLON)	// ；キー
#define COLON KEY(KEY_INPUT_COLON)	// ：キー
#define LBRACKET KEY(KEY_INPUT_LBRACKET)	// ［キー
#define RBRACKET KEY(KEY_INPUT_RBRACKET)	// ］キー
#define AT KEY(KEY_INPUT_AT)	// ＠キー
#define BACKSLASH KEY(KEY_INPUT_BACKSLASH)	// ＼キー
#define COMMA KEY(KEY_INPUT_COMMA)	// ，キー
#define CAPSLOCK KEY(KEY_INPUT_CAPSLOCK)	// CaspLockキー
#define PAUSE KEY(KEY_INPUT_PAUSE)	// PauseBreakキー
#define NUM0 KEY(KEY_INPUT_NUMPAD0)	// テンキー０
#define NUM1 KEY(KEY_INPUT_NUMPAD1)	// テンキー１
#define NUM2 KEY(KEY_INPUT_NUMPAD2)	// テンキー２
#define NUM3 KEY(KEY_INPUT_NUMPAD3)	// テンキー３
#define NUM4 KEY(KEY_INPUT_NUMPAD4)	// テンキー４
#define NUM5 KEY(KEY_INPUT_NUMPAD5)	// テンキー５
#define NUM6 KEY(KEY_INPUT_NUMPAD6)	// テンキー６
#define NUM7 KEY(KEY_INPUT_NUMPAD7)	// テンキー７
#define NUM8 KEY(KEY_INPUT_NUMPAD8)	// テンキー８
#define NUM9 KEY(KEY_INPUT_NUMPAD9)	// テンキー９
#define MULTIPLY KEY(KEY_INPUT_MULTIPLY)	// テンキー＊キー
#define ADD KEY(KEY_INPUT_ADD)	// テンキー＋キー
#define SUBTRACT KEY(KEY_INPUT_SUBTRACT)	// テンキー－キー
#define DECIMAL KEY(KEY_INPUT_DECIMAL)	// テンキー．キー
#define NUMSLASH KEY(KEY_INPUT_DIVIDE)	// テンキー／キー
#define NUMENTER KEY(KEY_INPUT_NUMPADENTER)	// テンキーのエンターキー
#define F1 KEY(KEY_INPUT_F1)	// Ｆ１キー
#define F2 KEY(KEY_INPUT_F2)	// Ｆ２キー
#define F3 KEY(KEY_INPUT_F3)	// Ｆ３キー
#define F4 KEY(KEY_INPUT_F4)	// Ｆ４キー
#define F5 KEY(KEY_INPUT_F5)	// Ｆ５キー
#define F6 KEY(KEY_INPUT_F6)	// Ｆ６キー
#define F7 KEY(KEY_INPUT_F7)	// Ｆ７キー
#define F8 KEY(KEY_INPUT_F8)	// Ｆ８キー
#define F9 KEY(KEY_INPUT_F9)	// Ｆ９キー
#define F10 KEY(KEY_INPUT_F10)	// Ｆ１０キー
#define F11 KEY(KEY_INPUT_F11)	// Ｆ１１キー
#define F12 KEY(KEY_INPUT_F12)	// Ｆ１２キー
#define A KEY(KEY_INPUT_A)	// Ａキー
#define B KEY(KEY_INPUT_B)	// Ｂキー
#define C KEY(KEY_INPUT_C)	// Ｃキー
#define D KEY(KEY_INPUT_D)	// Ｄキー
#define E KEY(KEY_INPUT_E)	// Ｅキー
#define F KEY(KEY_INPUT_F)	// Ｆキー
#define G KEY(KEY_INPUT_G)	// Ｇキー
#define H KEY(KEY_INPUT_H)	// Ｈキー
#define I KEY(KEY_INPUT_I)	// Ｉキー
#define J KEY(KEY_INPUT_J)	// Ｊキー
#define K KEY(KEY_INPUT_K)	// Ｋキー
#define L KEY(KEY_INPUT_L)	// Ｌキー
#define M KEY(KEY_INPUT_M)	// Ｍキー
#define N KEY(KEY_INPUT_N)	// Ｎキー
#define O KEY(KEY_INPUT_O)	// Ｏキー
#define P KEY(KEY_INPUT_P)	// Ｐキー
#define Q KEY(KEY_INPUT_Q)	// Ｑキー
#define R KEY(KEY_INPUT_R)	// Ｒキー
#define S KEY(KEY_INPUT_S)	// Ｓキー
#define T KEY(KEY_INPUT_T)	// Ｔキー
#define U KEY(KEY_INPUT_U)	// Ｕキー
#define V KEY(KEY_INPUT_V)	// Ｖキー
#define W KEY(KEY_INPUT_W)	// Ｗキー
#define X KEY(KEY_INPUT_X)	// Ｘキー
#define Y KEY(KEY_INPUT_Y)	// Ｙキー
#define Z KEY(KEY_INPUT_Z)	// Ｚキー
#define KEY0 KEY(KEY_INPUT_0)	// ０キー
#define KEY1 KEY(KEY_INPUT_1)	// １キー
#define KEY2 KEY(KEY_INPUT_2)	// ２キー
#define KEY3 KEY(KEY_INPUT_3)	// ３キー
#define KEY4 KEY(KEY_INPUT_4)	// ４キー
#define KEY5 KEY(KEY_INPUT_5)	// ５キー
#define KEY6 KEY(KEY_INPUT_6)	// ６キー
#define KEY7 KEY(KEY_INPUT_7)	// ７キー
#define KEY8 KEY(KEY_INPUT_8)	// ８キー
#define KEY9 KEY(KEY_INPUT_9)	// ９キー